name: "Postman -> OpenAPI -> Confluence (lists-based config)"
description: >
  Dynamically creates a config.yaml from user-supplied YAML lists (for multiple Postman sources and excludes),
  runs postman2openapi.py, then runs openapi2confluence.py.

inputs:
  postman-sources:
    description: |
      A YAML array of Postman JSON files to convert, e.g.:

      ```
      - "papi.postman_collection.json"
      - "my-other-collection.json"
      ```
    required: true

  exclude-paths:
    description: |
      A YAML array of paths to exclude, e.g.:

      ```
      - "/api/v1"
      - "/api/v2/old"
      ```
    required: false
    default: |
      []

  confluence-base-url:
    description: "Confluence base URL, e.g. https://yoursite.atlassian.net/wiki"
    required: true

  confluence-username:
    description: "Username/email for Confluence"
    required: true

  confluence-api-token:
    description: "API token for Confluence"
    required: true

  space-key:
    description: "Confluence space key, e.g. DOC"
    required: true

  parent-page-id:
    description: "Optional: ID of the parent page"
    required: false
    default: ""

  master-page-title:
    description: "Title for the master page"
    required: false
    default: "Platform Public API"

  partials-page-title:
    description: "Title for partial docs"
    required: false
    default: "API Endpoints"

  template-file:
    description: "Which Jinja template to use, e.g. custom_confluence.jinja"
    required: false
    default: "custom_confluence.jinja"

runs:
  using: "composite"
  steps:
    # 1) Check out code so we have scripts/ 
    - name: Check out code
      uses: actions/checkout@v3

    # 2) Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 3) Install Python dependencies
    - name: Install dependencies
      run: |
        pip install pyyaml requests jinja2

    # 4) Dynamically create config.yaml for postman2openapi.py 
    #    We'll directly echo user inputs into a file, 
    #    trusting that they're valid YAML arrays.
    - name: Create dynamic_config.yaml
      shell: bash
      run: |
        echo "excluded_paths: ${ { inputs.exclude-paths } }" > dynamic_config.yaml
        echo "" >> dynamic_config.yaml
        echo "sources: ${ { inputs.postman-sources } }" >> dynamic_config.yaml

        echo "Generated dynamic_config.yaml:"
        cat dynamic_config.yaml

    # 5) Convert ALL Postman files -> OpenAPI using postman2openapi.py
    - name: Convert Postman -> OpenAPI
      run: |
        python scripts/postman2openapi.py \
          --config dynamic_config.yaml \
          --search-dir .
        # This will produce .yaml for each source in the same folder(s) 
        # or wherever the script is coded to place them.

    # 6) Now run openapi2confluence on the MAIN doc 
    #    If you have multiple docs, you can do a loop or 
    #    pick the main one (like "papi.postman_collection.yaml").
    - name: Upload to Confluence
      run: |
        python scripts/openapi2confluence.py \
          --confluence-base-url "${{ inputs.confluence-base-url }}" \
          --username "${{ inputs.confluence-username }}" \
          --api-token "${{ inputs.confluence-api-token }}" \
          --space-key "${{ inputs.space-key }}" \
          --parent-page-id "${{ inputs.parent-page-id }}" \
          --master-file "papi.postman_collection.yaml" \
          --master-page-title "${{ inputs.master-page-title }}" \
          --partials-page-title "${{ inputs.partials-page-title }}" \
          --output-dir "partials_out" \
          --template-file "${{ inputs.template-file }}"
