openapi: 3.0.0
info:
  title: Platform PublicAPI
  version: 1.0.0
paths:
  /api/v3/parsecodebundle:
    get:
      summary: listparse codebundles
      responses:
        '200':
          description: Success
      parameters:
      - name: repoUrl
        in: query
        description: 'Query param: repoUrl'
        required: false
        schema:
          type: string
      - name: ref
        in: query
        description: 'Query param: ref'
        required: false
        schema:
          type: string
      - name: pathInRepo
        in: query
        description: 'Query param: pathInRepo'
        required: false
        schema:
          type: string
