openapi: 3.0.0
info:
  title: Platform PublicAPI
  version: 1.0.0
paths:
  /api/v3/workspaces/{wid}/slxs/{sid}/runbook/runs/{rrid}/runner-status:
    get:
      summary: Status
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/slxs/{sid}/runbook/runs/{rrid}/start:
    post:
      summary: Start
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/slxs/{sid}/runbook/runs/{rrid}:
    patch:
      summary: Step
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions/{rsid}/runrequests/{rqid}/mark-failed:
    put:
      summary: mark-failed
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions/{rid}/issues/{iid}/test:
    get:
      summary: Get Issue
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions/{rsid}:
    patch:
      summary: New request
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions:
    post:
      summary: Create
      responses:
        '200':
          description: Success
    get:
      summary: List
      responses:
        '200':
          description: Success
      parameters:
      - name: page-size
        in: query
        description: 'Query param: page-size'
        required: false
        schema:
          type: string
      - name: modified__lte
        in: query
        description: 'Query param: modified__lte'
        required: false
        schema:
          type: string
      - name: runrequest__runbook__name
        in: query
        description: 'Query param: runrequest__runbook__name'
        required: false
        schema:
          type: string
  /api/v3/workspaces/{wid}/slxs/{sid}/sli/chart:
    get:
      summary: Sli Chart
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions/{rid}/issues/{iid}:
    patch:
      summary: Update issue
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runsessions/{rid}/issues:
    get:
      summary: Get Issues
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/workflows/{id}/token:
    get:
      summary: Get Webhook Token
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/workflows/{id}/run:
    post:
      summary: Run
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/generate-workspace-builder-config:
    get:
      summary: Get Upload Config
      responses:
        '200':
          description: Success
      parameters:
      - name: hours
        in: query
        description: 'Query param: hours'
        required: false
        schema:
          type: string
  /api/v3/workspaces/{wid}/upload:
    get:
      summary: Upload
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/default-manifest/{type}:
    get:
      summary: defaut-manifest
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/reset-service-account:
    post:
      summary: Reset Workspace Service Account Password
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/integrate-slack:
    post:
      summary: Integrate Slack
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/sync-status:
    get:
      summary: Get Workspace Sync Status
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/index-status:
    get:
      summary: Get Workspace Index Status
      responses:
        '200':
          description: Success
      parameters:
      - name: detail
        in: query
        description: 'Query param: detail'
        required: false
        schema:
          type: string
  /api/v3/workspaces/{wid}/status:
    get:
      summary: Get Workspace Status
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/task-search:
    post:
      summary: Workspace Task Search
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/runner-token:
    get:
      summary: Get Runner Token
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}/slxoptions:
    get:
      summary: Get SLX Select Options
      responses:
        '200':
          description: Success
  /api/v3/workspaces/{wid}:
    get:
      summary: Get Workspace
      responses:
        '200':
          description: Success
